# Generated by Django 4.1.7 on 2023-06-01 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desciption', models.TextField()),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], default='unfinished', max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('degree_of_urgency', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_job', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='job.type')),
            ],
            options={
                'ordering': ('-deadline',),
            },
        ),
    ]
